name: 'Aiven DB switchover'
description: 'Promote recovery service as Master'

inputs:
  token:
    description: 'Aiven API token'
    required: false
  project:
    description: 'Aiven project hosting the services'
    required: true
  src_service_name:
    description: 'src_service_name'
    required: true
  dst_service_name:
    description: 'dst_service_name'
    required: true

outputs:
  myres:
    description: 'script output'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_PROJECT: ${{ inputs.project }}
    INPUT_TOKEN: ${{ inputs.token }}
    INPUT_SRC_SERVICE: ${{ inputs.src_service_name }}
    INPUT_DST_SERVICE: ${{ inputs.dst_service_name }}

