name: 'Aiven DB switchover'
description: 'Promote recovery service as Master'

inputs:
  token:
    description: 'Aiven API token'
    required: true
  project:
    description: 'Aiven project hosting the services'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.project }}

