name: 'Aiven DB switchover'
description: 'Promote recovery service as Master'

inputs:
  token:
    description: 'Aiven API token'
    required: false
  project:
    description: 'Aiven project hosting the services'
    required: true

outputs:
  myres:
    description: 'script output'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_PROJECT: ${{ inputs.project }}
    INPUT_TOKEN: ${{ inputs.token }}
    INPUT_EUW1_SERVICE: ${{ input.euw1_service_name }}
    INPUT_EUW4_SERVICE: ${{ input.euw4_service_name }}

